### PR TITLE
Inetegrate letter box image to demo.py

### PR DESCRIPTION
**Pull request by i3oi3o**
I manual test it.

Use the cute doggy image :dog: from here as test image. https://github.com/pjreddie/darknet/blob/master/data/dog.jpg

These are the flag that I use. 
`--data_format=NHWC --size=608 --input_img=dog.jpg --output_img=dog_yolo.jpg`

The main change is in utils.convert_to_original_size function .

Let me know if there is anything wrong. :smile:

@sagarkar10 You may want to take a look here. :satisfied:

### CODE REVIEW

**Comment by lucy3589** [comment]
> I manual test it.
> 
> Use the cute doggy image 🐶 from here as test image. https://github.com/pjreddie/darknet/blob/master/data/dog.jpg
> 
> These are the flag that I use.
> `--data_format=NHWC --size=608 --input_img=dog.jpg --output_img=dog_yolo.jpg`
> 
> The main change is in utils.convert_to_original_size function .
> 
> Let me know if there is anything wrong. 😄
> 
> @sagarkar10 You may want to take a look here. 😆

hello, Could you solve it  if you modifiy these code(mystic123 approved these changes on 3 Dec 2018)?

**Comment by i3oi3o** [comment]
@lucy3589 Umm.., Which issue do you want me to resolve?

**Comment by lucy3589** [comment]
i use darknet yolo, mAP is 0.9. but i use convert_weight_pb.py to convert weight, and use tf_yolo, but mAP is 0.7.

**Comment by i3oi3o** [comment]
Unfortunately, I couldn't. 
This need reverse engineering on both tensorflow and darknet.
It's very time consuming. With my current project, I probably cannot help much.
You can look at #77

**Comment by lucy3589** [comment]
> Unfortunately, I couldn't.
> This need reverse engineering on both tensorflow and darknet.
> It's very time consuming. With my current project workload, I don't have time.
> You can look at #77

thanks very much. I edit upsample, but it has low mAp.

**Pull request merged**
